updated zsh functions

diff --git a/common/.config/zsh/functions b/common/.config/zsh/functions
--- a/common/.config/zsh/functions
+++ b/common/.config/zsh/functions
@@ -1,28 +1,46 @@
 # Compress
 compress() {
-    if [[ -f "$@" ||  -d "$@" ]]; then
-    tar -czvf "$archive_name" "$@"
-    else
-        echo "not a valid file or dir"
+  if [[ $# -lt 2 ]]; then
+    echo "Please provide archive name or list of files!"
+    return 1
+  fi
+  local archive_name="$1"
+  shift
+  local check_files=true
+  for file in "$@"; do
+    if [[ ! -e "$file" ]]; then
+      echo "No file or directory found: '$file'"
+      check_files=false
     fi
+  done
+
+  if $check_files; then
+    tar -czvf "$archive_name".tar.gz "$@"
+    if [[ $? -eq 0 ]]; then
+      echo "Success: '$archive_name'.tar.gz created"
+    else
+      echo "Error: '$archive_name'.tar.gz was not created!"
+    fi
+  fi
+
 }
 # Decompress
 decompress() {
   if [[ -f $1 ]]; then
     case $1 in
-      *.tar.bz2)  tar xvjf "$1" ;;
-      *.tar.gz)   tar xvzf "$1" ;;
-      *.bz2)       bunzip2 "$1" ;;
-      *.rar)       unrar x "$1" ;;
-      *.gz)         gunzip "$1" ;;
-      *.tar)       tar xvf "$1" ;;
-      *.tbz2)     tar xvjf "$1" ;;
-      *.tgz)      tar xvzf "$1" ;;
-      *.zip)         unzip "$1" ;;
-      *.Z)      uncompress "$1" ;;
-      *.7z)           7z x "$1" ;;
-      *.xz)           unxz "$1" ;;
-            *)             echo "'$1' unknown compression" ;;
+      *.tar.bz2) tar xvjf "$1" ;;
+      *.tar.gz) tar xvzf "$1" ;;
+      *.bz2) bunzip2 "$1" ;;
+      *.rar) unrar x "$1" ;;
+      *.gz) gunzip "$1" ;;
+      *.tar) tar xvf "$1" ;;
+      *.tbz2) tar xvjf "$1" ;;
+      *.tgz) tar xvzf "$1" ;;
+      *.zip) unzip "$1" ;;
+      *.Z) uncompress "$1" ;;
+      *.7z) 7z x "$1" ;;
+      *.xz) unxz "$1" ;;
+      *) echo "'$1' unknown compression" ;;
     esac
   else
     echo "'$1' not a valid file"
@@ -31,11 +49,11 @@ decompress() {
 
 # Tmux
 function t() {
-    X=$#
-    [[ $X -eq 0 ]] || X=X
-    tmux new-session -A -s "$X"
-    tmux set-environment LC_ALL 'en_US.UTF-8'
-    tmux set-environment LANG 'en_US.UTF-8'
+  X=$#
+  [[ $X -eq 0 ]] || X=X
+  tmux new-session -A -s "$X"
+  tmux set-environment LC_ALL 'en_US.UTF-8'
+  tmux set-environment LANG 'en_US.UTF-8'
 }
 
 # Yazi
